# Generated by Django 3.1.5 on 2021-01-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20210120_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name_plural': 'URL表'},
        ),
        migrations.AddField(
            model_name='permission',
            name='caption',
            field=models.CharField(default=1, max_length=32, verbose_name='权限名'),
            preserve_default=False,
        ),
    ]
