# Generated by Django 3.1.5 on 2021-01-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20210120_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='code',
            field=models.CharField(default=1, max_length=32, verbose_name='动作'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='caption',
            field=models.CharField(max_length=32, verbose_name='动作名'),
        ),
    ]
