# Generated by Django 3.1.5 on 2021-01-20 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20210120_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name_plural': '操作表'},
        ),
        migrations.AlterModelOptions(
            name='permission2action',
            options={'verbose_name_plural': '权限表'},
        ),
        migrations.AlterModelOptions(
            name='permission2action2role',
            options={'verbose_name_plural': '角色分配权限表'},
        ),
        migrations.AlterField(
            model_name='action',
            name='caption',
            field=models.CharField(max_length=32, verbose_name='操作名'),
        ),
        migrations.AlterField(
            model_name='action',
            name='code',
            field=models.CharField(max_length=32, verbose_name='操作'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
                ('parent', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p', to='rbac.menu')),
            ],
        ),
    ]
